// <auto-generated />
using CasbinRBAC.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CasbinRBAC.Migrations
{
    [DbContext(typeof(CasbinDbContext<int>))]
    [Migration("20210428093010_EFCore-Adapter")]
    partial class EFCoreAdapter
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CasbinRBAC.Domain.Models.CasbinRule<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PType")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ptype");

                    b.Property<string>("V0")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("v0");

                    b.Property<string>("V1")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("v1");

                    b.Property<string>("V2")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("v2");

                    b.Property<string>("V3")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("v3");

                    b.Property<string>("V4")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("v4");

                    b.Property<string>("V5")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("v5");

                    b.HasKey("Id");

                    b.HasIndex("PType");

                    b.HasIndex("V0");

                    b.HasIndex("V1");

                    b.HasIndex("V2");

                    b.HasIndex("V3");

                    b.HasIndex("V4");

                    b.HasIndex("V5");

                    b.ToTable("casbin_rule");
                });
#pragma warning restore 612, 618
        }
    }
}
